[project]
name = "kompanion"
revision = "1.0"

[providers]
op = "onepassword://my.1password.com@kompanion"
local = "keyring://secretspec/cache/{project}/{profile}/{key}"

op-cached = { fallback = ["op"], cache = { provider = "local", max_age = "8h" } }

[profiles.default]
KEYSTORE_PASSWORD = { description = "keystore password", ref = { item = "kompanion_app_signing", field = "credential" } }

[profiles.development]
KEYSTORE_PASSWORD = { providers = [
  "op-cached",
] }

[profiles.ci]
KEYSTORE_PASSWORD = { providers = [
  "op",
] }
